# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
[[smithy-rs]]
message = "Made fluent operation structs cloneable"
references = ["aws-sdk-rust#254"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "Jacco"

[[aws-sdk-rust]]
message = "Made fluent operation structs cloneable"
references = ["aws-sdk-rust#254"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "Jacco"
